name: bookkeeping
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # internationalization support
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  # State management for widget
  provider: ^4.0.1
  # Database and sharePreference
  sqflite: ^1.2.0
  shared_preferences: ^0.5.6
  # Local File save
  path_provider: ^1.6.0
  # synchronized lock
  synchronized: ^2.2.0
  # Network request library. It also support restful api.
  dio: ^3.0.8
  # Toast for flutter
  fluttertoast: ^3.1.3
  # Flutter app info
  device_info: ^0.4.1+4
  # Permission manager for flutter app
  permission_handler: ^4.0.0
  # Check network
  connectivity: ^0.4.6+1
  # Refresh and load more component
  flutter_easyrefresh: ^2.0.6
  # Image Picker: select photo from gallery or take photos
  image_picker: ^0.6.3+1
  # Image edit or crop
  image_cropper: ^1.2.0
  # Date time format
  date_format: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/